---
title: Cincinnati Food Safety Program
author: andre
date: '2020-03-04'
slug: cincinnati-food-safety
categories:
  - Public Health
  - R
tags:
  - Food Safety
subtitle: ''
summary: ''
authors: []
lastmod: '2020-03-04T07:53:58-05:00'
featured: no
projects: []
output:
  blogdown::html_page:
    toc: true
---


```{r setup}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```


Image credit: [**Unsplash**](https://unsplash.com/photos/CpkOjOcXdUY)

* <span style="color: #fd7f6f;">Complaint</span>

* <span style="color: #7eb0d5;">Routine</span>

* <span style="color: #b2e061;">Initial</span>


```{r message=FALSE, warning=FALSE}
library("RSocrata")
library(tidyverse)
library(knitr)
library(DBI)
```


# Getting data

```{r echo=TRUE}
if (Sys.info()["sysname"] != "Linux"){
  con <- dbConnect(odbc::odbc(), Server = "127.0.0.1", Database = "cincinnati", 
    UID = "dre", PWD = "password", Port = 5432, .connection_string = "Driver={PostgreSQL ODBC Driver(ANSI)};", 
    timeout = 10)
  
} else {
  con <- dbConnect(odbc::odbc(), Server = "127.0.0.1", Database = "cincinnati", 
    UID = "dre", PWD = "password", Port = 5432, .connection_string = "Driver={PostgreSQL ANSI};", 
    timeout = 10)
}
```



```{r message=FALSE, warning=FALSE, include=FALSE}

## Install the required package with:
## install.packages("RSocrata")


if (!dbExistsTable(con, "foodsafety")){
  df <- read.socrata(
  "https://data.cincinnati-oh.gov/resource/rg6p-b3h3.json"#,
  #app_token = "YOURAPPTOKENHERE",
  #email     = "user@example.com",
  #password  = "fakepassword"
)
  dbWriteTable(con, "foodsafety", df, row.names=FALSE, append=TRUE)
}
dbExistsTable(con, "foodsafety")
```

# Column Names

```{sql connection=con, output.var = "results" , cache=TRUE}
SELECT column_name,data_type 
FROM information_schema.columns 
WHERE table_name = 'foodsafety';
```


```{r message=FALSE, warning=FALSE, cache=TRUE}
results %>% knitr::kable()
```

# Sample of Data

```{sql connection=con, output.var = "results" , cache=TRUE}
SELECT *
FROM foodsafety
LIMIT 5
```


```{r message=FALSE, warning=FALSE, cache=TRUE}
results %>% knitr::kable()
```

# Inspection Types 

```{sql connection=con, output.var = "results" , cache=TRUE}
SELECT DISTINCT insp_type
FROM foodsafety
```


```{r message=FALSE, warning=FALSE, cache=TRUE}
results %>% knitr::kable()
```




```{r}
results %>% head() %>% kable()
```


# Cities 

```{sql connection=con, output.var = "results" , cache=TRUE}
SELECT DISTINCT city AS Cities
FROM foodsafety
```


```{r message=FALSE, warning=FALSE, cache=TRUE}
results %>% knitr::kable()
```

# Postal Codes 

```{sql connection=con, output.var = "results"}
SELECT DISTINCT postal_code AS postal_codes, city
FROM foodsafety
```

```{r message=FALSE, warning=FALSE}
results %>% knitr::kable()
```




# Complaint Discriptions

```{sql connection=con, output.var = "results" , cache=TRUE}
SELECT DISTINCT violation_description AS complaint_description
FROM foodsafety
WHERE insp_type = 'COMPLAINT'
LIMIT 5
```

# And now? 

```{r message=FALSE, warning=FALSE, cache=TRUE}
results %>% knitr::kable()
```


# A Map

Will it go away?

```{sql connection=con, output.var = "results"}
ALTER TABLE foodsafety
  ALTER COLUMN "latitude" TYPE NUMERIC(14, 11) 
    USING ("latitude"::NUMERIC(14,11)),
  ALTER COLUMN "longitude" TYPE NUMERIC(14, 11) 
    USING ("longitude"::NUMERIC(14,11));
```

# And now?

```{sql connection=con, output.var = "results" }
SELECT  DISTINCT(postal_code), latitude, longitude, insp_type
FROM foodsafety
```

# Here is a nice plot. 

```{r}

```



# Build Site

```{r eval=FALSE, include=FALSE}
if (exists("con")) {
  library(DBI)
  dbDisconnect(con)
}

con.State
isPostgresqlIdCurrent(con)
dbCanConnect(con)

setwd("/home/dre/Documents/blog/")
blogdown::build_site()
blogdown::serve_site()
```




```{r}
library(leaflet)
pal <- colorFactor(c("#fd7f6f", "#7eb0d5", "#b2e061"), domain = c("COMPLAINT", "ROUTINE", "INITIAL"))

leafMap <- leaflet(results) %>% addTiles() %>%
  addCircleMarkers(
    lng=~longitude, lat=~latitude,
    color = ~pal(insp_type),
    stroke = FALSE, fillOpacity = 0.5,
    clusterOptions = markerClusterOptions()
  ) %>% addProviderTiles(providers$Esri.NatGeoWorldMap)
```


```{r}
library(htmlwidgets)
library(htmltools)

currentWD <- getwd()
dir.create("static/leaflet", showWarnings = FALSE)
setwd("static/leaflet")
saveWidget(leafMap, "leafMap.html")
setwd(currentWD)
```


The html that was saved with the saveWidget function can be called with the iframe html tag.

<iframe seamless src="/leaflet/leafMap.html" width="100%" height="500"></iframe>


* <span style="color: #fd7f6f;">Complaint</span>
* <span style="color: #7eb0d5;">Routine</span>
* <span style="color: #b2e061;">Initial</span>


# References

[Food Safety and Inspections](https://www.cincinnati-oh.gov/health/cincinnati-health-department-programs/food-safety-and-inspections-program/)

[Cincinnati Food Safety Program](https://data.cincinnati-oh.gov/Thriving-Neighborhoods/Cincinnati-Food-Safety-Program/rg6p-b3h3)

[SODA: Cincinnati Food Safety Program](https://dev.socrata.com/foundry/data.cincinnati-oh.gov/rg6p-b3h3)

[Connect to a Database](https://db.rstudio.com/getting-started/connect-to-database/)

[Databases using R](https://db.rstudio.com/)

[How to get a list column names and datatype of a table in PostgreSQL?](https://stackoverflow.com/questions/20194806/how-to-get-a-list-column-names-and-datatype-of-a-table-in-postgresql)

[Open A Socrata Dataset In Microsoft Power BI](https://support.socrata.com/hc/en-us/articles/115011432428)

[SQL Tutorial](https://www.w3schools.com/sql/default.asp)

[Leaflet for R](https://rstudio.github.io/leaflet/)

[Postgres columns of latitude and longitude from varchar to numeric](https://dba.stackexchange.com/questions/78580/postgres-columns-of-latitude-and-longitude-from-varchar-to-numeric)

[Using Leaflet and htmlwidgets in a Hugo-generated page](https://waterdata.usgs.gov/blog/leaflet/)

