---
title: 'A Map of the Total Number of Confirmed Coronavirus Cases in Each Country or Region'
author: andre
date: '2020-03-06'
slug: covid_19
categories:
  - Public Health
  - R
tags:
  - 'COVID-19'
subtitle: ''
summary: ''
authors: []
lastmod: '2020-03-04T07:53:58-05:00'
featured: no
projects: []
output:
  blogdown::html_page:
    toc: true
---

```{r setup, warning=FALSE, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(knitr)
library(plotly)
library(htmlwidgets)
library(htmltools)
library(leaflet)
library(stringr)
```

{{% alert note %}}
**<span style="color: #FF0000;">The data used for this map is outdated.</span>** Refer to this [**dashboard maintained by Johns Hopkins CSSE**](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) for up to date information. 
{{% /alert %}} 


The data that was used in generating this map is available on the Github page of the [Center for Systems Science and Engineering at Johns Hopkins University](https://github.com/CSSEGISandData). 

```{r message=FALSE, warning=FALSE, include=FALSE}
jhu_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"

covid <- read_csv(jhu_url) %>% rename(province = "Province/State", 
  country_region = "Country/Region") %>% pivot_longer(-c(province, 
  country_region, Lat, Long), names_to = "Date", values_to = "cumulative_cases")

covid_total <- covid %>%
  mutate(province = case_when(is.na(province) ~ country_region,
                              TRUE ~ province)) %>% 
  group_by(province) %>% 
  filter(cumulative_cases == max(cumulative_cases)) %>% 
  slice(1)

covid_total_map <- leaflet(covid_total) %>% addTiles() %>%
  addCircleMarkers(
    lng = ~ Long,
    lat = ~ Lat,
    radius = log(covid_total$cumulative_cases)*2,
    layerId = NULL,
    group = ~ country_region,
    stroke = TRUE,
    color = "red",
    weight = 5,
    opacity = 0.5,
    fill = TRUE,
    fillColor = "red",
    fillOpacity = 0.2,
    dashArray = NULL,
    popup = NULL,
    popupOptions = NULL,
    #clusterOptions = markerClusterOptions(),
    label = paste(covid_total$cumulative_cases),
    labelOptions = labelOptions(
      interactive = FALSE,
      clickable = FALSE,
      noHide = NULL,
      permanent = TRUE,
      className = "",
      direction = "auto",
      offset = c(0, 0),
      opacity = 1,
      textsize = "15px",
      textOnly = TRUE,
      style = NULL,
      zoomAnimation = NULL,
      sticky = TRUE
    )
  ) %>%
  #addPopups(popup = paste("Cumulative Cases:", covid_total$cumulative_cases)) %>%
  addLabelOnlyMarkers(label = paste(covid_total$cumulative_cases)) %>%
  addProviderTiles(providers$Esri)

currentWD <- getwd()
#dir.create("static/maps/covid-19", showWarnings = FALSE)
setwd("static/maps/covid-19")
saveWidget(covid_total_map, "covid_total_map.html")
setwd(currentWD)
```

```{r eval=FALSE, include=FALSE}
covid_total_map
```


<iframe seamless src="/maps/covid-19/covid_total_map.html" width="100%" height="500"></iframe>

Click [here](https://github.com/drevanzyl/blog/tree/master/content/post/covid-19) to get the code I used for creating this map.

# References

[Coronavirus COVID-19 Global Cases by Johns Hopkins CSSE](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)

[COVID-19 epidemiology with R](https://rviews.rstudio.com/2020/03/05/covid-19-epidemiology-with-r/)

[CSSE at Johns Hopkins University](https://github.com/CSSEGISandData)

[COVID-19 call-to-arms](https://timchurches.github.io/blog/posts/2020-03-06-covid-19-call-to-arms/)

[Analysing COVID-19 (2019-nCoV) outbreak data with R - part 2](https://timchurches.github.io/blog/posts/2020-03-01-analysing-covid-19-2019-ncov-outbreak-data-with-r-part-2/)

[Coronavirus: South Africa's President Ramaphosa warns of crisis](https://www.bbc.com/news/world-africa-51752974)


